### ISSUE TITLE
Support `FilteredList` requests.

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#101]
### Describe your ideas
`FilteredList` specific operations for ClickHouse. 
supports three different type of list

- ALL,
- PERSISTENT_ONLY,
- EPHEMERAL_ONLY

it's an optimization, and data transfer between Keeper and ClickHouse can be reduced.

@JackyWoo cc

**Comment by JackyWoo** [comment]
Ok thanks
