### ISSUE TITLE
Data race error while modify config

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#104]
### Description
We Implement a method `updateConfiguration` to update config (however, It‘s seem like only called during initialization). I guess it's for Dynamic Reconfiguration, but There is no complete implementation. 
```cpp
// RaftKeeper/src/Service/KeeperDispatcher.cpp
void KeeperDispatcher::updateConfiguration(const Poco::Util::AbstractConfiguration & config)
{
    auto diff = server->getConfigurationDiff(config);
    if (diff.empty())
        LOG_TRACE(log, "Configuration update triggered, but nothing changed for RAFT");
    else if (diff.size() > 1)
        LOG_WARNING(log, "Configuration changed for more than one server ({}) from cluster, it's strictly not recommended", diff.size());
    else
        LOG_INFO(log, "Configuration change size ({})", diff.size());

    for (auto & change : diff)
    {
        bool push_result = update_configuration_queue.push(change);
        if (!push_result)
            throw Exception(ErrorCodes::SYSTEM_ERROR, "Cannot push configuration update to queue");
    }
}

```
There is a background thread in nuraft::state_mgr that calls commit_conf to call NuRaftStateManager::save_config, which will modify cur_cluster_config, The main thread is calling updateConfiguration to read the modified cur_cluster_config, which will cause a data race

```cpp
// RaftKeeper/contrib/NuRaft/src/handle_commit.cxx
if (le->get_val_type() == log_val_type::conf) {
            commit_conf(index_to_commit, le);
        }
```

### How to reproduce 

found in https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/6852423348/job/18630926726?pr=102

I can easily add a mutex for NuRaftStateManager::cur_cluster_config to fix it. But i got a lot of confusion for intention for `updateConfiguration`.

@nicelulu @JackyWoo cc

**Comment by JackyWoo** [comment]
`ConfigReloader` will invoke `updateConfiguration ` in background.
