### ISSUE TITLE
Close socket before client get all data when handler `FourLetterWordCmd`

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#142]
### RaftKeeper version
2.0.3
### Description
Get Connection reset when using `FourLetterWordCmd`
### How to reproduce 
echo stat|nc 11.118.132.255 2181
RaftKeeper version: RaftKeeper v2.0.4
Clients:
 11.115.163.158:38942(recved=4679652,sent=4685458)
 11.62.71.249:24574(recved=5067762,sent=5075057)
 11.62.71.250:36014(recved=5381825,sent=5388387)
 11.118.126.147:64900(recved=5083387,sent=5090679)
 11.118.126.158:48382(recved=5159396,sent=5166985)
 11.118.135.39:53730(recved=5042596,sent=5049098)
 11.115.128.209:15208(recved=5498836,sent=5505599)
 11.102.66.75:52420(recved=5521839,sent=5529076)
 11.118.64.155:10138(recved=5344873,sent=5350979)
 11.115.163.171:50300(recved=5301892,sent=5308121)
 11.115.133.3:23170(recved=5120888,sent=5127194)
 10.203.24.118:23478(recved=0,sent=0)
 11.115.128.210:34748(recved=5125987,sent=5133551)
 10.199.138.8:25616(recved=14860,sent=14859)

Latency min/avg/max: 0/10/72518
Received: 4364557988
Sent : 4356565215
Connections: 13
Outstanding: 5
Zxid: 395838495277
Mode: leader
Node count: 13365943
Ncat: Connection reset by peer.

**Comment by JackyWoo** [comment]
When nc sending data to server, it will half close the connection, and waiting the result.  But RaftKeeper did not recoginze the half connection and it may close the connection in advance.
