### ISSUE TITLE
Slightly different from ZooKeeper MultiRead to ClickHouse `MultiRead`

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#161]
### RaftKeeper version
v.2.0.3
### Description
RaftKeeper is fully compatible with ZooKeeper, and can be accessed through the Zookeeper clients. However ClickHouse Keeper differs slightly from ZooKeeper in its implementation of `MultiRead` request.

Specifically, the difference lies in the error sub-responses related to MultiRead.For example, in MultiRead, we attempt to get a non-existent node.

Zookeeper MultiRead Response
```
MultiHeader(type=-1, done=False, err=-101) -101
```
type = -1 means it's an error reponse

ClickHouse Keeper  MultiRead Response
```
MultiHeader(type=4, done=False, err=-101)
```
ClickHouse Keeper keeps its request type, and  remove The body  which indicating the error type, as it is redundant and already present in the header.

**Comment by JackyWoo** [comment]
@lzydmxy you can push a PR to branch `compitable_with_clickhouse` which is compitable with ClickHouse and let's keep master compitable with Zookeeper
