### ISSUE TITLE
Just use `ZooKeeperResponsePtr` in response queue instead of  `FIFOBuffer`

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#172]
### Description

We use `FIFOBuffer queue` to store responses, which leads to unnecessary copy. We write buffer in `FIFOBuffer` , and move it to `FIFOBuffer queue`. But we need copy it to `send_buf` finally.

We can push `ZooKeeperResponsePtr` to response queue, and write on `send_buf` directly.

**Comment by JackyWoo** [comment]
We may send part of a response to client and the next loop send the rest part and a part of next response. Please take it into consideration.

**Comment by lzydmxy** [comment]
> We may send part of a response to client and in the next loop send the rest part and a part of next response. Please take it into consideration.

We may need a larger circular buffer to for repsonses. Each time, we can still send SENT_BUFFER_SIZE bytes to socket. This is achievable, but it would require modifying the performance testing. I am interested in exploring this further.
