### ISSUE TITLE
What makes RaftKeeper better than clickhouse-keeper ?

### ISSUE THREAD

**Issue by cangyin** [JDRaftKeeper/RaftKeeper#184]
### Describe your doubt

According to the benchmark, the performance of RaftKeeper is significantly higher than that of ZooKeeper. But the performance of clickhouse-keeper, from which RaftKeeper is derived, isn't so different with ZooKeeper. So what makes RaftKeeper better than clickhouse-keeper?

**Comment by JackyWoo** [comment]
As described in ReadMe, the key points are the pipeline execution framework and batch processing.

We extend the NuRaft pipeline execution framework by adding `fowarder` and `accumulator` at the head and `request processor` at the tail. 

And `accumulator` will enhance the batching execution which will significantly promote the performance.

In a work the execution framework of RaftKeeper works just like CPU which utilize pipeline execution and batch processing technology.

**Comment by cangyin** [comment]
Thanks for explaining!
