### ISSUE TITLE
[Enhancement] issue template is needed 

### ISSUE THREAD

**Issue by Henry2SS** [JDRaftKeeper/RaftKeeper#2]
We need an issue template which can simplify operations for contributors.

## 1 Issue: RaftKeeper Bug report
Problems and issues with code of RaftKeeper. If this doesn’t look right, [choose a different type.](https://github.com/JDRaftKeeper/RaftKeeper/issues/new)

Fields marked with an asterisk (*) are required.

title should start with `[Bug]`

Thank you very much for submitting feedback to RaftKeeper to help develop better.

### Search before asking *
Please make sure to search in the [issues](https://github.com/JDRaftKeeper/RaftKeeper/issues) first to see whether the same issue was reported already.

[ ] I had searched in the [issues](https://github.com/JDRaftKeeper/RaftKeeper/issues) and found no similar issues.

### Version *
What is the current version

Input box:  Please provide the version which you are using. The format like "version + commit id" is welcomed.

### What's the problem? *
Describe the bug.

Input box:  Please describe the problem in detail. The more detailed the better.

### What You Expected? *
Input box: 

### How to Reproduce? *
Input box:  Please try to give steps to facalitate the location of the problem.

### Anything Else
Input box: 

### Are you willing to submit PR?
We look forward to developers or users to help solve the Doris problem together. If you are willing to submit a PR to fix this problem, please tick it.

[ ] Yes I am willing to submit a PR!

### Code of Conduct
The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.

[ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

Thanks for contributing to RaftKeeper!

## 2 Issue: RaftKeeper enhancement
Add an enhanment for RaftKeeper. If this doesn’t look right, [choose a different type.](https://github.com/JDRaftKeeper/RaftKeeper/issues/new)

Fields marked with an asterisk (*) are required.

title should start with `[Enhancement]`

Thank you very much for submitting feedback to RaftKeeper to help develop better.

### Search before asking
Please make sure to search in the [issues](https://github.com/JDRaftKeeper/RaftKeeper/issues) first to see whether the same issue was reported already.

[ ] I had searched in the [issues](https://github.com/JDRaftKeeper/RaftKeeper/issues) and found no similar issues. *

### Description
Describe the enhancement you want, including the motivation.

Input box: 

### Solution
Add an overview of solution. And add some references if exist.

Input box: 

### Are you willing to submit PR?
We look forward to developers or users to help solve the Doris problem together. If you are willing to submit a PR to fix this problem, please tick it.

[ ] Yes I am willing to submit a PR!

### Code of Conduct
The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.

[ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

Thanks for contributing to RaftKeeper!

## 3 Issue: RaftKeeper feature request
Suggest an idea for RaftKeeper. If this doesn’t look right, [choose a different type.](https://github.com/JDRaftKeeper/RaftKeeper/issues/new)

Fields marked with an asterisk (*) are required.

title should start with `[Feature]`

Thank you very much for submitting feedback to RaftKeeper to help develop better.

### Search before asking
Please make sure to search in the [issues](https://github.com/JDRaftKeeper/RaftKeeper/issues) first to see whether the same issue was reported already.

[ ] I had searched in the [issues](https://github.com/JDRaftKeeper/RaftKeeper/issues) and found no similar issues. *

### Description
Describe your ideas and needs.

Input box: 

### Use Case
What problem does this feature mainly solve.

Input box: 

### Related Issue
Is there currently another issue associated with this?

Input box: 

### Are you willing to submit PR?
We look forward to developers or users to help solve the Doris problem together. If you are willing to submit a PR to fix this problem, please tick it.

[ ] Yes I am willing to submit a PR!

### Code of Conduct
The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.

[ ] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

Thanks for contributing to RaftKeeper!

Fields marked with an asterisk (*) are required.

**Comment by nicelulu** [comment]
Thanks. Closed by https://github.com/JDRaftKeeper/RaftKeeper/pull/3.
