### ISSUE TITLE
Keeper load snapshot without check object count

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#240]
### RaftKeeper version
v2.0.5
### Description
When the raftkeeper is accidentally killed during a snapshot, the snapshot data is not fully written to the disk (some objects loss). However, when the raftkeeper restarts, it can load and restart with the incomplete objects, which can lead to serious data loss issues.

**Comment by JackyWoo** [comment]
Fixed by #367
