### ISSUE TITLE
Some keeper utilities are added in ClickHouse repository.

### ISSUE THREAD

**Issue by cangyin** [JDRaftKeeper/RaftKeeper#259]
- [keeper-bench](https://github.com/ClickHouse/ClickHouse/tree/e795e0e028d45b654e099dee136a44e7ac5ed627/utils/keeper-bench)
- [keeper-data-dumper](https://github.com/ClickHouse/ClickHouse/tree/e795e0e028d45b654e099dee136a44e7ac5ed627/utils/keeper-data-dumper)
- [keeper-overload](https://github.com/ClickHouse/ClickHouse/tree/e795e0e028d45b654e099dee136a44e7ac5ed627/utils/keeper-overload)
- [zookeeper-cli](https://github.com/ClickHouse/ClickHouse/tree/e795e0e028d45b654e099dee136a44e7ac5ed627/utils/zookeeper-cli)
- [zookeeper-dump-tree](https://github.com/ClickHouse/ClickHouse/tree/e795e0e028d45b654e099dee136a44e7ac5ed627/utils/zookeeper-dump-tree)
- [zookeeper-remove-by-list](https://github.com/ClickHouse/ClickHouse/tree/e795e0e028d45b654e099dee136a44e7ac5ed627/utils/zookeeper-remove-by-list)

**Comment by JackyWoo** [comment]
Thanks for your issue. We already have benchmark tool in repo. We can add if there is any demand.

**Comment by JackyWoo** [comment]
Thanks for your issue. We already have benchmark tool in repo. We can add if there is any demand.
