### ISSUE TITLE
Please provide a document on migrating from Zookeeper to RaftKeeper.

### ISSUE THREAD

**Issue by lhcg** [JDRaftKeeper/RaftKeeper#33]
Is the same as clickhouse mainsite doc?

**Comment by nicelulu** [comment]
@lhcg Here is the migration doc https://github.com/JDRaftKeeper/RaftKeeper/blob/master/docs%2Fmigrate-from-zookeeper.md

**Comment by lhcg** [comment]
5.Translate Zookeeper data to RaftKeeper format and copy to other nodes.

[raft_node1]$ /path/to/RaftKeeper/raftkeeper converter --zookeeper-logs-dir /path_to_transfer_tmp_data_dir/log --zookeeper-snapshots-dir /path_to_transfer_tmp_data_dir/snapshot --output-dir /path_to_transfer_tmp_data_dir/output
[raft_node1]$ scp -r /path_to_transfer_tmp_data_dir/output root@raft_node2:/path_to_transfer_tmp_data_dir
[raft_node1]$ scp -r /path_to_transfer_tmp_data_dir/output root@raft_node3:/path_to_transfer_tmp_data_dir
6.Copy data to RaftKeeper data directory.

[raft_node1]$ cd /path/to/RaftKeeper && sh bin/stop.sh
[raft_node1]$ rm -rf data/* && mv /path_to_transfer_tmp_data_dir/output data/snapshot
[raft_node1]$ sh bin/start.sh

where is the /path/to/RaftKeeper/raftkeeper?
@nicelulu 
I had download the file from release

**Comment by nicelulu** [comment]
```/path/to/RaftKeeper/raftkeeper```  is raftkeeper binary file.

**Comment by lhcg** [comment]
<img width="789" alt="image" src="https://user-images.githubusercontent.com/8449870/230286399-dbe08a0d-8f56-45e9-9e5a-d8642e35553f.png">
if raft has more then 1 nodes, the script will exec each node?
@nicelulu

**Comment by nicelulu** [comment]
> if raft has more then 1 nodes, the script will exec each node? @nicelulu

No, need to execute ```mv /path_to_transfer_tmp_data_dir/output data/snapshot``` on each node.

**Comment by nicelulu** [comment]
@lhcg You need to use the zookeeper client to verify whether the raftkeeper cluster is fine. And need to modify node1, node2, node3 to real raft node host or ip.
