### ISSUE TITLE
Under ubuntu22.04 version, compilation and packaging failed

### ISSUE THREAD

**Issue by liuyuliang092** [JDRaftKeeper/RaftKeeper#36]
# Build on Ubuntu failed，Here are my steps，What should I do to build successfully

## environmental information
```
System version: Ubuntu 22.04 LTS
clang version: Ubuntu clang version 14.0.0-1ubuntu1
cmake version: cmake version 3.22.1
```
## step1
```
# install tools
sudo apt-get install cmake llvm-13
```
![result](https://github.com/liuyuliang092/pictureAndIcons/blob/main/cmake-llvm.png)
## step2
```
# clone project
git clone https://github.com/JDRaftKeeper/RaftKeeper.git
```
![result](https://github.com/liuyuliang092/pictureAndIcons/blob/main/RaftKeeper.png)
## step3
```
cd RaftKeeper && git submodule sync && git submodule update --init --recursive
```
![result](https://github.com/liuyuliang092/pictureAndIcons/blob/main/git.png)
## step4
```
# build project
export CC=`which clang` CXX=`which clang++`
```
![result](https://github.com/liuyuliang092/pictureAndIcons/blob/main/export.png)
## step5
```
/bin/bash build.sh
```
![result](https://github.com/liuyuliang092/pictureAndIcons/blob/main/error.png)
## Step 5 executes an error report, modifies the CMakeLists.txt in the root directory of RaftKeeper, and adds the following configuration at the file entry
```
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
```
## Re-execute after modification
```
/bin/bash build.sh
```
![result](https://github.com/liuyuliang092/pictureAndIcons/blob/main/error-2.png)

**Comment by Hooollin** [comment]
Thanks for your feedback. I will look into this issue as soon as possible.

**Comment by Hooollin** [comment]
When I reached Step5 following your process, I encountered the same issue.  I added the 5 lines you mentioned to the top-level `CMakeLists.txt` and deleted the `CMakeCache.txt` under `build`.  `/bin/bash build.sh` works.

Deleting `CMakeCache.txt` before running `/bin/bash build.sh` might be helpful.

**Comment by Hooollin** [comment]
And I think you should use 
```
export CC=`which clang-13` CXX=`which clang++-13`
```
in step4. If you don't have clang-13 in your system, you can install it by `sudo apt-get install clang-13`.

**Comment by liuyuliang092** [comment]
Thank you for your suggestion, according to the method you provided, it has been successfully solved
