### ISSUE TITLE
Save the file count information in the snapshot to ensure it is a complete snapshot file and prevent data loss.

### ISSUE THREAD

**Issue by lzydmxy** [JDRaftKeeper/RaftKeeper#363]
### RaftKeeper version
v2.1.1
### Description
Found in test https://github.com/JDRaftKeeper/RaftKeeper/actions/runs/11028685908/job/30630210401?pr=361
We kill RaftKeeper force, only file `/snapshot/snapshot_20240925082106_1_10_1` created
```
2024-09-25T08:23:54.1793916Z 2024.09.25 08:21:06.528459 [ 12 ] <Information> KeeperSnapshotStore: Creating async snapshot v3 with approximately data_object_count 1, total_obj_count 4, next zxid 9, next session id 3
2024-09-25T08:23:54.1794582Z 2024.09.25 08:21:06.528524 [ 12 ] <Information> KeeperSnapshotStore: Begin create snapshot map object, map size 2, path /snapshot/snapshot_20240925082106_1_10_1
```
After that, we restart RaftKeeper, and loss all data
```
2024-09-25T08:23:54.1804421Z 2024.09.25 08:21:06.805812 [ 178 ] <Information> KeeperSnapshotStore.parseObjectThread#0: Parsing snapshot object /snapshot/snapshot_20240925082106_1_10_1
2024-09-25T08:23:54.1804963Z 2024.09.25 08:21:06.806267 [ 178 ] <Information> KeeperSnapshotStore: Open snapshot object /snapshot/snapshot_20240925082106_1_10_1 for read, file size 82
2024-09-25T08:23:54.1805298Z 2024.09.25 08:21:06.806400 [ 171 ] <Information> KeeperSnapshotStore: Parsing snapshot objects costs 2ms
2024-09-25T08:23:54.1805669Z 2024.09.25 08:21:06.806464 [ 171 ] <Information> KeeperSnapshotStore: Building data tree from snapshot objects
...
2024-09-25T08:23:54.1821628Z 2024.09.25 08:21:06.808007 [ 171 ] <Information> KeeperSnapshotStore: Loading snapshot done: nodes 1, ephemeral nodes 0, sessions 0, session_id_counter 3, zxid 9
```

**Comment by lzydmxy** [comment]
Maybe we can save snapshot obj count in snapshot_obj1 or save it in file name, what's your suggestion @JackyWoo

**Comment by JackyWoo** [comment]
@lzydmxy please add it to `snapshot_obj_1`

**Comment by lzydmxy** [comment]
> I think we would better squash snapshot_obj 1-3 to a single one in the future
ok, I open an issue about it #364

**Comment by lzydmxy** [comment]
2024.09.30 10:41:45.126341 [ 39 ] <Information> KeeperSnapshotStore: Parsing snapshot objects costs 1764ms
2024.09.30 10:41:45.126369 [ 39 ] <Information> KeeperSnapshotStore: Building data tree from snapshot objects
2024.09.30 10:41:45.126425 [ 47 ] <Information> KeeperSnapshotStore.buildDataTreeThread#1: Filling bucket 1 in data tree
2024.09.30 10:41:45.126448 [ 44 ] <Information> KeeperSnapshotStore.buildDataTreeThread#4: Filling bucket 4 in data tree
2024.09.30 10:41:45.126477 [ 46 ] <Information> KeeperSnapshotStore.buildDataTreeThread#2: Filling bucket 2 in data tree
2024.09.30 10:41:45.126494 [ 48 ] <Information> KeeperSnapshotStore.buildDataTreeThread#3: Filling bucket 3 in data tree
2024.09.30 10:41:45.126508 [ 43 ] <Information> KeeperSnapshotStore.buildDataTreeThread#7: Filling bucket 7 in data tree
2024.09.30 10:41:45.126523 [ 43 ] <Information> KeeperSnapshotStore.buildDataTreeThread#7: Building children set for data tree bucket 7
2024.09.30 10:41:45.126540 [ 49 ] <Information> KeeperSnapshotStore.buildDataTreeThread#5: Filling bucket 5 in data tree
2024.09.30 10:41:45.126572 [ 42 ] <Information> KeeperSnapshotStore.buildDataTreeThread#6: Filling bucket 6 in data tree
2024.09.30 10:41:45.126599 [ 42 ] <Information> KeeperSnapshotStore.buildDataTreeThread#6: Building children set for data tree bucket 6
2024.09.30 10:41:45.126610 [ 45 ] <Information> KeeperSnapshotStore.buildDataTreeThread#0: Filling bucket 0 in data tree
2024.09.30 10:41:45.359806 [ 49 ] <Information> KeeperSnapshotStore.buildDataTreeThread#5: Building children set for data tree bucket 5
2024.09.30 10:41:45.411537 [ 45 ] <Information> KeeperSnapshotStore.buildDataTreeThread#0: Building children set for data tree bucket 0
2024.09.30 10:41:45.435030 [ 47 ] <Information> KeeperSnapshotStore.buildDataTreeThread#1: Building children set for data tree bucket 1
2024.09.30 10:41:45.488662 [ 45 ] <Information> KeeperSnapshotStore.buildDataTreeThread#0: Filling bucket 8 in data tree
2024.09.30 10:41:45.488698 [ 45 ] <Information> KeeperSnapshotStore.buildDataTreeThread#0: Building children set for data tree bucket 8
2024.09.30 10:41:45.511980 [ 46 ] <Information> KeeperSnapshotStore.buildDataTreeThread#2: Building children set for data tree bucket 2
2024.09.30 10:41:45.513605 [ 48 ] <Information> KeeperSnapshotStore.buildDataTreeThread#3: Building children set for data tree bucket 3
2024.09.30 10:41:45.522956 [ 47 ] <Information> KeeperSnapshotStore.buildDataTreeThread#1: Filling bucket 9 in data tree
2024.09.30 10:41:45.522971 [ 47 ] <Information> KeeperSnapshotStore.buildDataTreeThread#1: Building children set for data tree bucket 9
2024.09.30 10:41:45.524617 [ 44 ] <Information> KeeperSnapshotStore.buildDataTreeThread#4: Building children set for data tree bucket 4
2024.09.30 10:41:45.585939 [ 46 ] <Information> KeeperSnapshotStore.buildDataTreeThread#2: Filling bucket 10 in data tree
2024.09.30 10:41:45.585968 [ 46 ] <Information> KeeperSnapshotStore.buildDataTreeThread#2: Building children set for data tree bucket 10
2024.09.30 10:41:45.586201 [ 48 ] <Information> KeeperSnapshotStore.buildDataTreeThread#3: Filling bucket 11 in data tree
2024.09.30 10:41:45.586219 [ 48 ] <Information> KeeperSnapshotStore.buildDataTreeThread#3: Building children set for data tree bucket 11
2024.09.30 10:41:45.608597 [ 44 ] <Information> KeeperSnapshotStore.buildDataTreeThread#4: Filling bucket 12 in data tree
2024.09.30 10:41:45.608614 [ 44 ] <Information> KeeperSnapshotStore.buildDataTreeThread#4: Building children set for data tree bucket 12
2024.09.30 10:41:46.474168 [ 41 ] <Information> FileLogStore: shutdown background raft log fsync thread.
2024.09.30 10:41:46.474341 [ 39 ] <Error> Application: RK::Exception: Can not find parent for node d3f8341e19ef096ba23b379522240945_572_576_1
2024.09.30 10:41:46.474366 [ 39 ] <Information> Application: Shutting down RaftKeeper.
2024.09.30 10:41:46.474404 [ 40 ] <Information> BaseDaemon: Stop SignalListener thread

**Comment by JackyWoo** [comment]
@lzydmxy why added the comment?

**Comment by lzydmxy** [comment]
> @lzydmxy why added the comment?

 We should try last valid Snapshot when start up. I open another issue #368  for this, so just ignore it.
