### ISSUE TITLE
Release v2.0.0 has SAXParseException

### ISSUE THREAD

**Issue by Henry2SS** [JDRaftKeeper/RaftKeeper#39]
Problems and issues with code of RaftKeeper. If this doesn’t look right, choose a [choose a different type.](https://github.com/JDRaftKeeper/RaftKeeper/issues/new)

### RaftKeeper version
Release v2.0.0

### How to reproduce 
deploy a cluster of 5 raft node. using <internal_port> under tag <cluster>.

Erorr:

 ```
<Error> ConfigReloader: Error loading config from 'conf/config.xml': 
Poco::Exception. Code: 1000, 
e.code() = 0, e.displayText() = 
SAXParseException: Tag mismatch in 'conf/config.xml', line 127 column 37, 
Stack trace (when copying this message, always include the lines below):
```

### Expected behavior
run properly

**Comment by Hooollin** [comment]
Can you provide the `config.xml` file causing the exception?

**Comment by Henry2SS** [comment]
> Can you provide the `config.xml` file causing the exception?

1. download the Release v2.0.0 pack.
2. find the conf/config.xml
3. line 127 column 37

there is a tag mismatch

**Comment by Henry2SS** [comment]
> > Can you provide the `config.xml` file causing the exception?
> 
> 1. download the Release v2.0.0 pack.
> 2. find the conf/config.xml
> 3. line 127 column 37
> 
> there is a tag mismatch

**Comment by JackyWoo** [comment]
It is alreay fixed
