### ISSUE TITLE
Could not pass CI, stuck on build-and-test

### ISSUE THREAD

**Issue by Hooollin** [JDRaftKeeper/RaftKeeper#41]
Problems and issues with code of RaftKeeper. If this doesn’t look right, choose a [choose a different type.](https://github.com/JDRaftKeeper/RaftKeeper/issues/new)

### Describe your doubt
I pass all integration tests on my machine, but fails everytime on build-and-test.

**Comment by JackyWoo** [comment]
@Hooollin just ignore it, details in #42

**Comment by JackyWoo** [comment]
Fixed by #147
