### ISSUE TITLE
Clang-format all source files

### ISSUE THREAD

**Issue by Hooollin** [JDRaftKeeper/RaftKeeper#62]
### Description

There exists a `.clang-format` file, but not all source file is clang-formatted. We can do clang-format on every single RaftKeeper source file.

### Are you willing to submit PR?
yes.

**Comment by Hooollin** [comment]
By the way, I notice the mismatch between style-check and `.clang-format`, as #63 illustrates.

**Comment by JackyWoo** [comment]
We prefer keep the current code style. Format all will destroy some code layout.

For example:

```
auto some_function = [] (UInt8 argu)
{
    ...
}
```
