### ISSUE TITLE
Allow document start for yaml

### ISSUE THREAD

**Issue by Hooollin** [JDRaftKeeper/RaftKeeper#67]
### Description

Resources are separated by `---` when there are multiple resources in one yaml file, which is needed by PR #52. If we set `document-start` to false, yamllint won't allow the existence of `---` in yaml file. Can we set `document-start` to true to allow PR #52 passing style check?

### Are you willing to submit PR?
yes.

**Comment by JackyWoo** [comment]
@Hooollin  can we just suppress the checking in your yaml file?

**Comment by Hooollin** [comment]
> @Hooollin can we just suppress the checking in your yaml file?

It's feasible. I'll do that in #52.
